name: Deploy Bicep file
on:
  push:
    branches:
      - main

jobs:
  commision-resources:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'IaC') || 
      contains(join(github.event.commits.*.message), 'IaC')
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        failOnStdErr: true
