name: Deploy Bicep file
on:
  push:
    branches:
      - main

jobs:
  commision-resources:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'IaC') || 
      contains(join(github.event.commits.*.message), 'IaC')
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

     # Install Bicep CLI if not already present
    - name: Install Bicep CLI
      run: |
        az bicep install
        az bicep upgrade

    # Run Bicep What-If Deployment
    - name: Run Bicep What-If
      run: |
        az deployment group what-if \
          --name WhatIfDeployment \
          --resource-group ${{ secrets.AZURE_RG }} \
          --template-file ./main.bicep \
          --parameters env=Development

    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: zavalita1
        minimum-approvals: 1
        issue-title: "Deploy IaC"
        issue-body: "Please approve or deny this IaC application"
        exclude-workflow-initiator-as-approver: false
        fail-on-denial: true

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: 'env=Development'
        failOnStdErr: true
